### ISSUE TITLE
issue with overflow

### ISSUE THREAD

**Issue by avmaisak** [alanyong91/ellipsis-pagination#1]
@alanyong91 good day,

i'm using your lib for creating my custom paginator with Angular / TypeScript. 

So, there are some problems.

invoke example
```
    return truncatePagination({
      prefix: 2, // optional, default is 2
      suffix: 2, // optional, default is 2
      currentPage: this.pagination.pageNumber, // required
      displayNumber: 5, // required, number of pager to display
      totalPage: this.pagination.totalPages // required
    })
```

it looks good

![image](https://user-images.githubusercontent.com/1219921/142216113-c5a3ff89-4abe-4c80-94e9-97659a6e0db4.png)

but, when i clicked to the last page

![image](https://user-images.githubusercontent.com/1219921/142216174-ee07a85a-6ed6-4271-a69b-a78c03af6d06.png)

result is:

![image](https://user-images.githubusercontent.com/1219921/142216324-95166132-bfa2-4d03-8ca6-ea47284353cd.png)

and server response as expected

```
pageNumber: 22
pageSize: 10
totalItems: 213
totalPages: 22
```

**Comment by alanyong91** [comment]
Hi @avmaisak. I published new update with bug fixed in the package. Could you update the package and try again?

**Comment by avmaisak** [comment]
@alanyong91 , problem still remains, with another use cases:

![image](https://user-images.githubusercontent.com/1219921/142370375-a476d4a9-53c7-4b37-8c9f-1ae916ff5131.png)

next, change page to the last

![image](https://user-images.githubusercontent.com/1219921/142370254-59fac997-dad4-4266-b287-8d76645b75c8.png)

or change to the 

![image](https://user-images.githubusercontent.com/1219921/142370438-d9534bf9-400c-4e6b-aff6-3c3ccb94292f.png)

result is:

![image](https://user-images.githubusercontent.com/1219921/142370469-c21c0427-6c89-4888-bbba-5500b0a0d1c6.png)

**Comment by alanyong91** [comment]
@avmaisak may I know what is the value of `this.pagination.totalPages` and `this.pagination.pageNumber`? 

Also, can you check which version of this package you using right now? Should be `"ellipsis-pagination": "^1.0.3"`

**Comment by avmaisak** [comment]
``

> @avmaisak may I know what is the value of `this.pagination.totalPages` and `this.pagination.pageNumber`?
> 
> Also, can you check which version of this package you using right now? Should be `"ellipsis-pagination": "^1.0.3"`

@alanyong91 

```
"ellipsis-pagination": "^1.0.3",

```

**Comment by alanyong91** [comment]
That weird. It's working from my side. 

![image](https://user-images.githubusercontent.com/17760752/142372829-f1cfe6b9-d60d-45e0-beb3-f943ac4aac75.png)

Can you try uninstall and reinstall again the package?

**Comment by avmaisak** [comment]
> That weird. It's working from my side.
> 
> ![image](https://user-images.githubusercontent.com/17760752/142372829-f1cfe6b9-d60d-45e0-beb3-f943ac4aac75.png)
> 
> Can you try uninstall and reinstall again the package?

@alanyong91 , done. Problem still remains (((

**Comment by avmaisak** [comment]
payload to reproduce
```
currentPage: 21
displayNumber: 9
prefix: 2
suffix: 2
totalPage: 22
```

**Comment by alanyong91** [comment]
for now may be you set `displayNumber` to 5 first. I need some time to check the bug.

**Comment by avmaisak** [comment]
> for now may be you set `displayNumber` to 5 first. I need some time to check the bug.

@alanyong91  - with displayNumber === 5 it works! ))
